version: '3'

services:
  1ccommunicationserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 1ccommunicationserver
    links:
      - postgres:postgres
    environment:
      - POSTGRES_URL=postgres:5432/cs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8181:8181"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=cs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
